"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from plex_api_client import PlexAPI
from plex_api_client.models import operations


def test_log_log_line():
    s = PlexAPI(
        access_token="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.log.log_line(
        level=operations.Level.THREE, message="Test log message", source="Postman"
    )
    assert res.status_code == 200


def test_log_log_multi_line():
    s = PlexAPI(
        access_token="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.log.log_multi_line(
        request="level=4&message=Test%20message%201&source=postman\n"
        + "level=3&message=Test%20message%202&source=postman\n"
        + "level=1&message=Test%20message%203&source=postman"
    )
    assert res.status_code == 200


def test_log_enable_paper_trail():
    s = PlexAPI(
        access_token="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.log.enable_paper_trail()
    assert res.status_code == 200
