"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class MediaTypeString(str, Enum):
    r"""The type of media content in the Plex library. This can represent videos, music, or photos."""

    MOVIE = "movie"
    TV_SHOW = "show"
    SEASON = "season"
    EPISODE = "episode"
    ARTIST = "artist"
    ALBUM = "album"
    TRACK = "track"
    PHOTO_ALBUM = "photoalbum"
    PHOTO = "photo"
    COLLECTION = "collection"
