"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TranscodeType(str, Enum):
    VIDEO = "video"
    MUSIC = "music"
    AUDIO = "audio"
    SUBTITLES = "subtitles"
