"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from plex_api_client import utils
from plex_api_client.types import BaseModel
import pydantic
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class CheckForUpdatesUpdaterErrorsTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]
    status: NotRequired[int]


class CheckForUpdatesUpdaterErrors(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    status: Optional[int] = None


class CheckForUpdatesUpdaterResponseBodyData(BaseModel):
    errors: Optional[List[CheckForUpdatesUpdaterErrors]] = None

    raw_response: Annotated[Optional[httpx.Response], pydantic.Field(exclude=True)] = (
        None
    )
    r"""Raw HTTP response; suitable for custom response parsing"""


class CheckForUpdatesUpdaterResponseBody(Exception):
    r"""Unauthorized - Returned if the X-Plex-Token is missing from the header or query."""

    data: CheckForUpdatesUpdaterResponseBodyData

    def __init__(self, data: CheckForUpdatesUpdaterResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, CheckForUpdatesUpdaterResponseBodyData)


class CheckForUpdatesErrorsTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]
    status: NotRequired[int]


class CheckForUpdatesErrors(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    status: Optional[int] = None


class CheckForUpdatesResponseBodyData(BaseModel):
    errors: Optional[List[CheckForUpdatesErrors]] = None

    raw_response: Annotated[Optional[httpx.Response], pydantic.Field(exclude=True)] = (
        None
    )
    r"""Raw HTTP response; suitable for custom response parsing"""


class CheckForUpdatesResponseBody(Exception):
    r"""Bad Request - A parameter was not specified, or was specified incorrectly."""

    data: CheckForUpdatesResponseBodyData

    def __init__(self, data: CheckForUpdatesResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, CheckForUpdatesResponseBodyData)
