"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from plex_api_client.models.errors import PlexAPIError
from plex_api_client.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSearchResultsSearchErrorsTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]
    status: NotRequired[int]


class GetSearchResultsSearchErrors(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    status: Optional[int] = None


class GetSearchResultsUnauthorizedData(BaseModel):
    errors: Optional[List[GetSearchResultsSearchErrors]] = None

    raw_response: Annotated[Optional[httpx.Response], pydantic.Field(exclude=True)] = (
        None
    )
    r"""Raw HTTP response; suitable for custom response parsing"""


@dataclass(frozen=True)
class GetSearchResultsUnauthorized(PlexAPIError):
    r"""Unauthorized - Returned if the X-Plex-Token is missing from the header or query."""

    data: GetSearchResultsUnauthorizedData = field(hash=False)

    def __init__(
        self,
        data: GetSearchResultsUnauthorizedData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetSearchResultsErrorsTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]
    status: NotRequired[int]


class GetSearchResultsErrors(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    status: Optional[int] = None


class GetSearchResultsBadRequestData(BaseModel):
    errors: Optional[List[GetSearchResultsErrors]] = None

    raw_response: Annotated[Optional[httpx.Response], pydantic.Field(exclude=True)] = (
        None
    )
    r"""Raw HTTP response; suitable for custom response parsing"""


@dataclass(frozen=True)
class GetSearchResultsBadRequest(PlexAPIError):
    r"""Bad Request - A parameter was not specified, or was specified incorrectly."""

    data: GetSearchResultsBadRequestData = field(hash=False)

    def __init__(
        self,
        data: GetSearchResultsBadRequestData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
