"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from plex_api_client import utils
from plex_api_client.types import BaseModel
import pydantic
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetUserDetailsAuthenticationErrorsTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]
    status: NotRequired[int]


class GetUserDetailsAuthenticationErrors(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    status: Optional[int] = None


class GetUserDetailsAuthenticationResponseBodyData(BaseModel):
    errors: Optional[List[GetUserDetailsAuthenticationErrors]] = None

    raw_response: Annotated[Optional[httpx.Response], pydantic.Field(exclude=True)] = (
        None
    )
    r"""Raw HTTP response; suitable for custom response parsing"""


class GetUserDetailsAuthenticationResponseBody(Exception):
    r"""Unauthorized - Returned if the X-Plex-Token is missing from the header or query."""

    data: GetUserDetailsAuthenticationResponseBodyData

    def __init__(self, data: GetUserDetailsAuthenticationResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(
            self.data, GetUserDetailsAuthenticationResponseBodyData
        )


class GetUserDetailsErrorsTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]
    status: NotRequired[int]


class GetUserDetailsErrors(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    status: Optional[int] = None


class GetUserDetailsResponseBodyData(BaseModel):
    errors: Optional[List[GetUserDetailsErrors]] = None

    raw_response: Annotated[Optional[httpx.Response], pydantic.Field(exclude=True)] = (
        None
    )
    r"""Raw HTTP response; suitable for custom response parsing"""


class GetUserDetailsResponseBody(Exception):
    r"""Bad Request - A parameter was not specified, or was specified incorrectly."""

    data: GetUserDetailsResponseBodyData

    def __init__(self, data: GetUserDetailsResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, GetUserDetailsResponseBodyData)
