workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi:main
targets:
    plexpy:
        target: python
        source: plexapi
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            labelOverride: 
                fixedValue: PlexPy
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-python-plexpy
