"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "plex-api-client"
__version__: str = "0.22.0"
__openapi_doc_version__: str = "0.0.3"
__gen_version__: str = "2.506.0"
__user_agent__: str = "speakeasy-sdk/python 0.22.0 2.506.0 0.0.3 plex-api-client"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
